name: 'Fork Repository'
description: 'An action that forks changelog'
inputs:
  workflow_id:
    description: 'The ID of the workflow'
    required: true
    default: "***"
  token:
    description: 'The GitHub token to use.'
    required: false
    default: ${{ github.token }}
  branch:
    description: 'The branch to create a changelog for.'
    required: false
  commit_regex:
    description: 'A regular expression used to filter out commits.'
    required: false
outputs:
  changelog:
    description: 'The generated changelog'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'folder-plus'
  color: 'purple'