name: Test
on: [push] 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:18-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Matyrobbrt/actions-changelog@00581a8d85ddfbd4c1c1d7e0290e8bd0b50fee84
        id: changelog
        with:
          branch: testing
          workflow_id: release.yml
      - run: echo "${{ steps.changelog.outputs.changelog }}"