name: Test
on: [push] 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:18-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Matyrobbrt/actions-changelog@3ee9dea8ff411dee9e57654c64d655452cf000ac
        id: changelog
        with:
          branch: testing
          workflow_id: release.yml
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.changelog.outputs.changelog }}"