name: Test
on: [push] 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:18-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Matyrobbrt/actions-changelog@d265960c72508e443c7b82cb65b3a679e45051e8
        id: changelog
        with:
          branch: testing
          workflow_id: release.yml
          token: ${{ github.token }}
      - run: echo "${{ steps.changelog.outputs.changelog }}"