name: Test
on: [push] 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:18-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Matyrobbrt/actions-changelog@efc40d3ecefe14ef4739101248cf4db5f54908f0
        id: changelog
        with:
          branch: testing
          workflow_id: release.yml
      - run: echo "${{ steps.changelog.outputs.changelog }}"