name: Test
on: [push] 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:18-jdk
      options: --user root
    steps:
      - run: apt update && apt install git -y && git --version
      - run: git config --global --add safe.directory /__w/actions-changelog/actions-changelog
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Matyrobbrt/actions-changelog@fa9c5e5be596d609a923df1f04e1ac690bebdd4d
        id: changelog
        with:
          branch: testing
          workflow_id: test.yml
          token: ${{ github.token }}
      - run: echo "${{ steps.changelog.outputs.changelog }}"