name: Test
on: [push] 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:18-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Matyrobbrt/actions-changelog@2766f7143c6b8ef417cc3e5375c8b8a17935062f
        id: changelog
        with:
          branch: testing
          workflow_id: release.yml
      - run: echo "${{ steps.changelog.outputs.changelog }}"